-- Migration: Dynamic Moderation Blocklist (backward compatible)
-- Date: 2024-12-16
-- Purpose: Ensure moderation_blocklist supports phrase-based filtering while remaining compatible with older schema

-- ============================================================================
-- 1) Ensure table exists (older deployments may already have it)
--    NOTE: If the table already exists, this does nothing.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.moderation_blocklist (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern text,
  category text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),

  -- Newer fields (optional / forward-compatible)
  phrase text,
  language text,
  severity text NOT NULL DEFAULT 'block' CHECK (severity IN ('block', 'warn')),
  updated_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  notes text
);

-- ============================================================================
-- 2) Add missing columns safely (for older schema already in production)
-- ============================================================================
ALTER TABLE public.moderation_blocklist ADD COLUMN IF NOT EXISTS phrase text;
ALTER TABLE public.moderation_blocklist ADD COLUMN IF NOT EXISTS language text;
ALTER TABLE public.moderation_blocklist ADD COLUMN IF NOT EXISTS severity text NOT NULL DEFAULT 'block';
ALTER TABLE public.moderation_blocklist ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.moderation_blocklist ADD COLUMN IF NOT EXISTS created_by uuid;
ALTER TABLE public.moderation_blocklist ADD COLUMN IF NOT EXISTS notes text;

-- Backfill phrase from legacy "pattern" where phrase is missing
UPDATE public.moderation_blocklist
SET phrase = COALESCE(phrase, pattern)
WHERE phrase IS NULL AND pattern IS NOT NULL;

-- ============================================================================
-- 3) Indexes (no duplicates)
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_moderation_blocklist_phrase
  ON public.moderation_blocklist (phrase);

CREATE INDEX IF NOT EXISTS idx_moderation_blocklist_severity
  ON public.moderation_blocklist (severity);

CREATE INDEX IF NOT EXISTS idx_moderation_blocklist_is_active
  ON public.moderation_blocklist (is_active);

-- ============================================================================
-- 4) RLS (read allowed for anon/auth; writes blocked unless you later add policies)
-- ============================================================================
ALTER TABLE public.moderation_blocklist ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read blocklist" ON public.moderation_blocklist;

CREATE POLICY "Public can read blocklist" ON public.moderation_blocklist
  FOR SELECT
  USING (true);

-- ============================================================================
-- 5) updated_at trigger (safe because updated_at column exists now)
-- ============================================================================
CREATE OR REPLACE FUNCTION public.update_moderation_blocklist_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS moderation_blocklist_set_updated_at ON public.moderation_blocklist;

CREATE TRIGGER moderation_blocklist_set_updated_at
BEFORE UPDATE ON public.moderation_blocklist
FOR EACH ROW
EXECUTE FUNCTION public.update_moderation_blocklist_updated_at();
